### ISSUE TITLE
Try improving this webapp.

### ISSUE THREAD

**Issue by mainak2003** [mainak2003/WebApp#1]

**Comment by codesmith25103** [comment]
I want to work on this issue. Please assign me this issue?

**Comment by mainak2003** [comment]
Go ahead @codesmith25103 !!

**Comment by singhkaran202** [comment]
Hello @mainak2003 , I'd love to work on this if that's OK.
Could you please assign me this?

**Comment by mainak2003** [comment]
Go ahead @singhkaran202 !! I need 3-4 people to work on this issue!

**Comment by aniketsinha2002** [comment]
Can you please assign me this? I'm already working on it!

**Comment by mainak2003** [comment]
Fine! @aniketsinha2002 go ahead!!

**Comment by singhkaran202** [comment]
@mainak2003, Could you please elaborate that what will be the use of this web app, so according to that we can add contents and other functionalities in it.

**Comment by mainak2003** [comment]
Sure! It's a small software solution providing early age startup! We make Webapps for small businesses and help them to reach more potential customers!!

**Comment by singhkaran202** [comment]
@mainak2003 bro, css file is missing in the project

**Comment by GAURAVKR007** [comment]
hey i can add some styling and coloring in your project with a CSS File
can you assign this to me ?

**Comment by mainak2003** [comment]
Sure @GAURAVKR007 go for it !!

**Comment by mainak2003** [comment]
I can assign this to at max 4 people, so others please don't comment until I unassign anyone! You can create a new issue if you want to contribute.

**Comment by GAURAVKR007** [comment]
Pls give me permission to add my code. 
That merge Conflict was gone out of hand so i decided to erase all my commit and rewrite it again According to new file.

**Comment by mainak2003** [comment]
@GAURAVKR007 I've already assigned you. You can create another pull request after required changes.

**Comment by GAURAVKR007** [comment]
remote: Permission to mainak2003/Webapp.git denied to GAURAVKR007.
fatal: unable to access 'https://github.com/mainak2003/Webapp.git/': The requested URL returned error: 403

**Comment by mainak2003** [comment]
@GAURAVKR007 @codesmith25103 @singhkaran202  

Are you guys working on this project to improve this website further? Do reply so that I can assign other peoples.

**Comment by mainak2003** [comment]
Same here @GAURAVKR007 :)

**Comment by OneAutumLeaf** [comment]
hi @mainak2003 
I can add card animation to website can u assign it to me.

**Comment by mainak2003** [comment]
Sure! Go ahead @OneAutumLeaf !!

**Comment by OneAutumLeaf** [comment]
hi @mainak2003 
It looks like you don't have login page . I can add it.

**Comment by mainak2003** [comment]
Yaa go ahead @OneAutumLeaf !

**Comment by OneAutumLeaf** [comment]
hi @mainak2003 
I have created login page just signup page is left then i will send PR request.

**Comment by OneAutumLeaf** [comment]
hi @mainak2003 
Can u create another issue regarding Navbar not sticking to the screen after scrolling down under the Hacktober fest.
